import FreeCAD


def _shape_objects(doc):
    return [obj for obj in doc.Objects
            if hasattr(obj, "Shape") and obj.Shape is not None]


class BulletEmitterFeature:
    """Non-physical configuration for spawning bodies from a source shape."""

    def __init__(self, obj):
        obj.addProperty("App::PropertyLink", "EmissionSource", "Emitter",
                        "Volume or surface used to choose emission positions")
        obj.addProperty("App::PropertyLink", "TemplateObject", "Emitter",
                        "Legacy primary object copied for emitted bodies")
        obj.addProperty("App::PropertyLinkList", "TemplateObjects", "Emitter",
                        "Objects available for emission")
        obj.addProperty("App::PropertyFloatList", "TemplateRatios", "Emitter",
                        "Percentage assigned to each emitted object")
        obj.addProperty("App::PropertyLinkList", "GeneratedLinks", "Emitter",
                        "Simulation links generated by this emitter")
        obj.addProperty("App::PropertyLink", "StartConditionObject", "Conditions",
                        "Optional shape that starts emission when touched by an active body")
        obj.addProperty("App::PropertyLink", "StopConditionObject", "Conditions",
                        "Optional shape that stops future emissions when touched by an active body")
        obj.addProperty("App::PropertyEnumeration", "StartConditionType", "Conditions",
                        "Start emission by time or when an active body touches a shape")
        obj.StartConditionType = ["Time", "Collision Object"]
        obj.addProperty("App::PropertyEnumeration", "EndConditionType", "Conditions",
                        "End emission by time or when an active body touches a shape")
        obj.EndConditionType = ["Time", "Collision Object"]
        obj.addProperty("App::PropertyBool", "Enabled", "Emitter",
                        "Include this emitter in Bullet Physics simulations")
        obj.Enabled = True
        obj.addProperty("App::PropertyEnumeration", "BodyType", "Emission",
                        "Type assigned to each emitted body; the emitter is non-physical")
        obj.BodyType = ["Active", "Passive"]
        obj.addProperty("App::PropertyInteger", "Count", "Emission",
                        "Total number of bodies to emit")
        obj.Count = 1
        obj.addProperty("App::PropertyFloat", "StartTime", "Emission",
                        "First emission time in seconds; delay after Start condition when set")
        obj.StartTime = 0.0
        obj.addProperty("App::PropertyFloat", "EndTime", "Emission",
                        "Final emission time in seconds; 0 keeps emitting until the simulation stops")
        obj.EndTime = 1.0
        obj.addProperty("App::PropertyVector", "Orientation", "Emission",
                        "Base emitted orientation in degrees (X, Y, Z)")
        obj.Orientation = FreeCAD.Vector(0, 0, 0)
        obj.addProperty("App::PropertyVector", "OrientationRandomness", "Emission",
                        "Per-axis orientation randomness: 0 = none, 1 = maximum")
        obj.OrientationRandomness = FreeCAD.Vector(0, 0, 0)
        obj.addProperty("App::PropertyInteger", "RandomSeed", "Emission",
                        "Random seed. 0 creates a new random sequence each simulation")
        obj.RandomSeed = 0
        obj.addProperty("App::PropertyFloat", "Velocity", "Active Body",
                        "Initial launch speed in m/s. Ignored for Passive bodies")
        obj.Velocity = 0.0
        obj.addProperty("App::PropertyVector", "Direction", "Active Body",
                        "Initial launch direction. Ignored for Passive bodies")
        obj.Direction = FreeCAD.Vector(0, 0, 1)
        obj.addProperty("App::PropertyVector", "DirectionRandomness", "Active Body",
                        "Per-axis direction randomness: 0 = none, 1 = maximum")
        obj.DirectionRandomness = FreeCAD.Vector(0, 0, 0)
        obj.addProperty("App::PropertyInteger", "DirectionRandomSeed", "Active Body",
                        "Direction random seed. 0 creates a new random sequence each simulation")
        obj.DirectionRandomSeed = 0
        obj.addProperty("App::PropertyFloat", "Density", "Active Body",
                        "Material density in kg/m³ for active emitted bodies")
        obj.Density = 1000.0
        obj.addProperty("App::PropertyFloat", "Restitution", "Material",
                        "Bounciness from 0 to 1")
        obj.Restitution = 0.3
        obj.addProperty("App::PropertyFloat", "Friction", "Material",
                        "Friction coefficient")
        obj.Friction = 0.5
        obj.Proxy = self

    def execute(self, obj):
        pass

    def onDocumentRestored(self, obj):
        if not hasattr(obj, "GeneratedLinks"):
            obj.addProperty("App::PropertyLinkList", "GeneratedLinks", "Emitter",
                            "Simulation links generated by this emitter")
        if not hasattr(obj, "TemplateObjects"):
            obj.addProperty("App::PropertyLinkList", "TemplateObjects", "Emitter",
                            "Objects available for emission")
            template = getattr(obj, "TemplateObject", None)
            obj.TemplateObjects = [template] if template is not None else []
        if not hasattr(obj, "TemplateRatios"):
            obj.addProperty("App::PropertyFloatList", "TemplateRatios", "Emitter",
                            "Percentage assigned to each emitted object")
            templates = list(getattr(obj, "TemplateObjects", []))
            obj.TemplateRatios = [100.0] if len(templates) == 1 else []
        if not hasattr(obj, "Enabled"):
            obj.addProperty("App::PropertyBool", "Enabled", "Emitter",
                            "Include this emitter in Bullet Physics simulations")
            obj.Enabled = True
        if not hasattr(obj, "StartConditionObject"):
            obj.addProperty("App::PropertyLink", "StartConditionObject", "Conditions",
                            "Optional shape that starts emission when touched by an active body")
        if not hasattr(obj, "StopConditionObject"):
            obj.addProperty("App::PropertyLink", "StopConditionObject", "Conditions",
                            "Optional shape that stops future emissions when touched by an active body")
        if not hasattr(obj, "StartConditionType"):
            obj.addProperty("App::PropertyEnumeration", "StartConditionType", "Conditions",
                            "Start emission by time or when an active body touches a shape")
            obj.StartConditionType = ["Time", "Collision Object"]
            if getattr(obj, "StartConditionObject", None) is not None:
                obj.StartConditionType = "Collision Object"
        if not hasattr(obj, "EndConditionType"):
            obj.addProperty("App::PropertyEnumeration", "EndConditionType", "Conditions",
                            "End emission by time or when an active body touches a shape")
            obj.EndConditionType = ["Time", "Collision Object"]
            if getattr(obj, "StopConditionObject", None) is not None:
                obj.EndConditionType = "Collision Object"
        if not hasattr(obj, "RandomSeed"):
            obj.addProperty("App::PropertyInteger", "RandomSeed", "Emission",
                            "Random seed. 0 creates a new random sequence each simulation")
            obj.RandomSeed = 0
        if not hasattr(obj, "DirectionRandomness"):
            obj.addProperty("App::PropertyVector", "DirectionRandomness", "Active Body",
                            "Per-axis direction randomness: 0 = none, 1 = maximum")
            obj.DirectionRandomness = FreeCAD.Vector(0, 0, 0)
        if not hasattr(obj, "DirectionRandomSeed"):
            obj.addProperty("App::PropertyInteger", "DirectionRandomSeed", "Active Body",
                            "Direction random seed. 0 creates a new random sequence each simulation")
            obj.DirectionRandomSeed = 0

    def __getstate__(self):
        return None

    def __setstate__(self, state):
        return None


class EmitterPanel:
    """Task panel for selecting an emission source and emitted object."""

    def __init__(self, emitter):
        from PySide import QtWidgets

        self._emitter = emitter
        if hasattr(emitter.Proxy, "onDocumentRestored"):
            emitter.Proxy.onDocumentRestored(emitter)
        self.form = QtWidgets.QWidget()
        self.form.setWindowTitle("Emitter")
        layout = QtWidgets.QVBoxLayout(self.form)

        source_group = QtWidgets.QGroupBox("Objects")
        source_form = QtWidgets.QFormLayout(source_group)
        self.source_combo = QtWidgets.QComboBox()
        self._populate_object_combos()
        source_form.addRow("Emission source:", self.source_combo)
        self.template_table = QtWidgets.QTableWidget(0, 3)
        self.template_table.setHorizontalHeaderLabels(
            ["Object to emit", "Ratio (%)", ""])
        self.template_table.verticalHeader().setVisible(False)
        self.template_table.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.template_table.setMinimumHeight(96)
        self.template_table.setColumnWidth(0, 180)
        self.template_table.setColumnWidth(1, 90)
        self.template_table.setColumnWidth(2, 58)
        source_form.addRow("Emitted objects:", self.template_table)
        template_buttons = QtWidgets.QWidget()
        template_buttons_layout = QtWidgets.QHBoxLayout(template_buttons)
        template_buttons_layout.setContentsMargins(0, 0, 0, 0)
        self.add_template_button = QtWidgets.QPushButton("Add object")
        self.template_ratio_total = QtWidgets.QLabel()
        template_buttons_layout.addWidget(self.add_template_button)
        template_buttons_layout.addWidget(self.template_ratio_total)
        template_buttons_layout.addStretch()
        source_form.addRow("", template_buttons)
        self._populate_template_table()
        layout.addWidget(source_group)

        condition_group = QtWidgets.QGroupBox("Start / End Conditions")
        condition_form = QtWidgets.QFormLayout(condition_group)
        self.start_condition_type_combo = QtWidgets.QComboBox()
        self.start_condition_type_combo.addItems(["Time", "Collision Object"])
        self.start_condition_type_combo.setCurrentText(
            getattr(emitter, "StartConditionType", "Time"))
        self.end_condition_type_combo = QtWidgets.QComboBox()
        self.end_condition_type_combo.addItems(["Time", "Collision Object"])
        self.end_condition_type_combo.setCurrentText(
            getattr(emitter, "EndConditionType", "Time"))
        self.start_spin = self._time_spin(getattr(emitter, "StartTime", 0.0))
        self.end_spin = self._time_spin(getattr(emitter, "EndTime", 1.0))
        self.start_condition_object_combo = QtWidgets.QComboBox()
        self.end_condition_object_combo = QtWidgets.QComboBox()
        self._populate_condition_object_combos()
        self.start_condition_value = QtWidgets.QStackedWidget()
        self.start_condition_value.addWidget(self.start_spin)
        self.start_condition_value.addWidget(self.start_condition_object_combo)
        self.end_condition_value = QtWidgets.QStackedWidget()
        self.end_condition_value.addWidget(QtWidgets.QWidget())
        self.end_condition_value.addWidget(self.end_condition_object_combo)
        condition_form.addRow("Start condition:", self.start_condition_type_combo)
        condition_form.addRow("Start value:", self.start_condition_value)
        condition_form.addRow("End condition:", self.end_condition_type_combo)
        condition_form.addRow("End time (s):", self.end_spin)
        condition_form.addRow("End collision object:", self.end_condition_value)
        condition_form.addRow(QtWidgets.QLabel(
            "The emitter stops when its end time is reached or its end collision object is touched. "
            "Set end time to 0 for collision-only stopping."))
        layout.addWidget(condition_group)

        emission_group = QtWidgets.QGroupBox("Emission")
        emission_form = QtWidgets.QFormLayout(emission_group)
        self.enabled_check = QtWidgets.QCheckBox("Enabled")
        self.enabled_check.setChecked(getattr(emitter, "Enabled", True))
        self.type_combo = QtWidgets.QComboBox()
        self.type_combo.addItems(["Active", "Passive"])
        self.type_combo.setCurrentText(getattr(emitter, "BodyType", "Active"))
        self.count_spin = QtWidgets.QSpinBox()
        self.count_spin.setRange(1, 10000)
        self.count_spin.setValue(max(1, getattr(emitter, "Count", 1)))
        orientation_widget, self.orientation_spins = self._vector_input(
            emitter.Orientation, -360.0, 360.0, 2, "Euler angles in degrees")
        orientation_random_widget, self.orientation_random_spins = self._vector_input(
            emitter.OrientationRandomness, 0.0, 1.0, 3,
            "Per-axis values from 0 (none) to 1 (maximum)")
        self.random_seed_spin = QtWidgets.QSpinBox()
        self.random_seed_spin.setRange(0, 2147483647)
        self.random_seed_spin.setValue(max(0, getattr(emitter, "RandomSeed", 0)))
        emission_form.addRow(self.enabled_check)
        emission_form.addRow("Emitted body type:", self.type_combo)
        emission_form.addRow("Count:", self.count_spin)
        emission_form.addRow("Orientation (deg):", orientation_widget)
        emission_form.addRow("Orientation randomness:", orientation_random_widget)
        emission_form.addRow("Random seed:", self.random_seed_spin)
        layout.addWidget(emission_group)

        launch_group = QtWidgets.QGroupBox("Active Body Launch")
        launch_form = QtWidgets.QFormLayout(launch_group)
        self.velocity_spin = QtWidgets.QDoubleSpinBox()
        self.velocity_spin.setRange(0.0, 100000.0)
        self.velocity_spin.setDecimals(4)
        self.velocity_spin.setSuffix(" m/s")
        self.velocity_spin.setValue(max(0.0, getattr(emitter, "Velocity", 0.0)))
        direction_widget, self.direction_spins = self._vector_input(
            emitter.Direction, -100000.0, 100000.0, 4, "Direction vector")
        direction_random_widget, self.direction_random_spins = self._vector_input(
            getattr(emitter, "DirectionRandomness", FreeCAD.Vector()), 0.0, 1.0, 3,
            "Per-axis values from 0 (none) to 1 (maximum)")
        self.direction_random_seed_spin = QtWidgets.QSpinBox()
        self.direction_random_seed_spin.setRange(0, 2147483647)
        self.direction_random_seed_spin.setValue(
            max(0, getattr(emitter, "DirectionRandomSeed", 0)))
        self.passive_note = QtWidgets.QLabel("Passive object selected: velocity and direction are ignored.")
        self.passive_note.setWordWrap(True)
        launch_form.addRow("Velocity:", self.velocity_spin)
        launch_form.addRow("Direction:", direction_widget)
        launch_form.addRow("Direction randomness:", direction_random_widget)
        launch_form.addRow("Direction random seed:", self.direction_random_seed_spin)
        launch_form.addRow(self.passive_note)
        layout.addWidget(launch_group)
        layout.addStretch()

        self.source_combo.currentIndexChanged.connect(self._save)
        self.add_template_button.clicked.connect(lambda: self._add_template_row())
        self.start_condition_type_combo.currentIndexChanged.connect(
            self._on_condition_type_changed)
        self.end_condition_type_combo.currentIndexChanged.connect(
            self._on_condition_type_changed)
        self.start_condition_object_combo.currentIndexChanged.connect(self._save)
        self.end_condition_object_combo.currentIndexChanged.connect(self._save)
        self.enabled_check.toggled.connect(self._save)
        self.type_combo.currentTextChanged.connect(self._on_type_changed)
        self.count_spin.valueChanged.connect(self._save)
        self.start_spin.valueChanged.connect(self._save)
        self.end_spin.valueChanged.connect(self._save)
        for spin in (self.orientation_spins + self.orientation_random_spins
                     + self.direction_spins + self.direction_random_spins):
            spin.valueChanged.connect(self._save)
        self.random_seed_spin.valueChanged.connect(self._save)
        self.direction_random_seed_spin.valueChanged.connect(self._save)
        self.velocity_spin.valueChanged.connect(self._save)
        self._update_body_type()
        self._update_condition_controls()

    @staticmethod
    def _vector_input(vector, minimum, maximum, decimals, tooltip):
        from PySide import QtWidgets
        widget = QtWidgets.QWidget()
        layout = QtWidgets.QHBoxLayout(widget)
        layout.setContentsMargins(0, 0, 0, 0)
        layout.setSpacing(4)
        spins = []
        for axis, value in zip(("X", "Y", "Z"), (vector.x, vector.y, vector.z)):
            spin = QtWidgets.QDoubleSpinBox()
            spin.setRange(minimum, maximum)
            spin.setDecimals(decimals)
            spin.setValue(value)
            spin.setFixedWidth(88)
            spin.setToolTip(f"{axis} axis: {tooltip}")
            axis_label = QtWidgets.QLabel(axis)
            axis_label.setFixedWidth(12)
            layout.addWidget(axis_label)
            layout.addWidget(spin)
            spins.append(spin)
        return widget, tuple(spins)

    @staticmethod
    def _vector_from_spins(spins):
        return FreeCAD.Vector(*(spin.value() for spin in spins))

    @staticmethod
    def _time_spin(value):
        from PySide import QtWidgets
        spin = QtWidgets.QDoubleSpinBox()
        spin.setRange(0.0, 100000.0)
        spin.setDecimals(4)
        spin.setValue(max(0.0, value))
        return spin

    def _populate_object_combos(self):
        combo = self.source_combo
        combo.blockSignals(True)
        combo.clear()
        combo.addItem("(none)", None)
        selected = 0
        for obj in _shape_objects(self._emitter.Document):
            combo.addItem(obj.Label, obj)
            if obj == self._emitter.EmissionSource:
                selected = combo.count() - 1
        combo.setCurrentIndex(selected)
        combo.blockSignals(False)

    def _template_values(self):
        templates = [obj for obj in getattr(self._emitter, "TemplateObjects", [])
                     if obj is not None]
        if not templates:
            template = getattr(self._emitter, "TemplateObject", None)
            templates = [template] if template is not None else []
        ratios = list(getattr(self._emitter, "TemplateRatios", []))
        if len(ratios) != len(templates):
            ratios = [100.0] if len(templates) == 1 else [0.0] * len(templates)
        return templates, ratios

    def _populate_template_table(self):
        templates, ratios = self._template_values()
        for template, ratio in zip(templates, ratios):
            self._add_template_row(template, ratio)
        if not templates:
            self._add_template_row()
        self._update_template_ratio_total()

    def _add_template_row(self, template=None, ratio=0.0, _checked=False):
        from PySide import QtWidgets

        row = self.template_table.rowCount()
        self.template_table.insertRow(row)
        combo = QtWidgets.QComboBox()
        combo.addItem("(none)", None)
        selected = 0
        for obj in _shape_objects(self._emitter.Document):
            combo.addItem(obj.Label, obj)
            if obj == template:
                selected = combo.count() - 1
        combo.setCurrentIndex(selected)
        ratio_spin = QtWidgets.QDoubleSpinBox()
        ratio_spin.setRange(0.0, 100.0)
        ratio_spin.setDecimals(3)
        ratio_spin.setSingleStep(1.0)
        ratio_spin.setSuffix(" %")
        ratio_spin.setValue(max(0.0, min(100.0, ratio)))
        remove_button = QtWidgets.QToolButton()
        remove_button.setText("Remove")
        remove_button.setToolTip("Remove this emitted object")
        remove_button.clicked.connect(
            lambda _checked=False, button=remove_button: self._remove_template_row(button))
        combo.currentIndexChanged.connect(self._save)
        ratio_spin.valueChanged.connect(self._save)
        self.template_table.setCellWidget(row, 0, combo)
        self.template_table.setCellWidget(row, 1, ratio_spin)
        self.template_table.setCellWidget(row, 2, remove_button)
        self._update_template_ratio_total()

    def _remove_template_row(self, button):
        if self.template_table.rowCount() <= 1:
            return
        for row in range(self.template_table.rowCount()):
            if self.template_table.cellWidget(row, 2) is button:
                self.template_table.removeRow(row)
                break
        self._save()

    def _template_table_values(self):
        templates = []
        ratios = []
        for row in range(self.template_table.rowCount()):
            template = self.template_table.cellWidget(row, 0).currentData()
            if template is None:
                continue
            templates.append(template)
            ratios.append(self.template_table.cellWidget(row, 1).value())
        return templates, ratios

    def _update_template_ratio_total(self):
        _templates, ratios = self._template_table_values()
        total = sum(ratios)
        valid = bool(ratios) and abs(total - 100.0) < 1e-6
        self.template_ratio_total.setText(
            f"Total: {total:.3f}%" +
            (" (deterministic sequence)" if valid else " (must be 100%)"))

    def _populate_condition_object_combos(self):
        for combo, current in (
                (self.start_condition_object_combo,
                 getattr(self._emitter, "StartConditionObject", None)),
                (self.end_condition_object_combo,
                 getattr(self._emitter, "StopConditionObject", None))):
            combo.blockSignals(True)
            combo.clear()
            combo.addItem("(none)", None)
            selected = 0
            for obj in _shape_objects(self._emitter.Document):
                combo.addItem(obj.Label, obj)
                if obj == current:
                    selected = combo.count() - 1
            combo.setCurrentIndex(selected)
            combo.blockSignals(False)

    def _save(self, *_args):
        emitter = self._emitter
        emitter.EmissionSource = self.source_combo.currentData()
        templates, ratios = self._template_table_values()
        emitter.TemplateObjects = templates
        emitter.TemplateRatios = ratios
        emitter.TemplateObject = templates[0] if templates else None
        emitter.StartConditionType = self.start_condition_type_combo.currentText()
        emitter.EndConditionType = self.end_condition_type_combo.currentText()
        emitter.StartConditionObject = self.start_condition_object_combo.currentData()
        emitter.StopConditionObject = self.end_condition_object_combo.currentData()
        emitter.Enabled = self.enabled_check.isChecked()
        emitter.BodyType = self.type_combo.currentText()
        emitter.Count = self.count_spin.value()
        emitter.StartTime = self.start_spin.value()
        emitter.EndTime = self.end_spin.value()
        emitter.Orientation = self._vector_from_spins(self.orientation_spins)
        emitter.OrientationRandomness = self._vector_from_spins(
            self.orientation_random_spins)
        emitter.RandomSeed = self.random_seed_spin.value()
        emitter.Velocity = self.velocity_spin.value()
        emitter.Direction = self._vector_from_spins(self.direction_spins)
        emitter.DirectionRandomness = self._vector_from_spins(
            self.direction_random_spins)
        emitter.DirectionRandomSeed = self.direction_random_seed_spin.value()
        self._update_template_ratio_total()
        emitter.Document.recompute()

    def _on_type_changed(self, *_args):
        self._update_body_type()
        self._save()

    def _on_condition_type_changed(self, *_args):
        self._update_condition_controls()
        self._save()

    def _update_condition_controls(self):
        self.start_condition_value.setCurrentIndex(
            1 if self.start_condition_type_combo.currentText() == "Collision Object" else 0)
        self.end_condition_value.setCurrentIndex(
            1 if self.end_condition_type_combo.currentText() == "Collision Object" else 0)

    def _update_body_type(self):
        passive = self.type_combo.currentText() == "Passive"
        self.velocity_spin.setEnabled(not passive)
        for spin in self.direction_spins + self.direction_random_spins:
            spin.setEnabled(not passive)
        self.direction_random_seed_spin.setEnabled(not passive)
        self.passive_note.setVisible(passive)

    def accept(self):
        self._save()
        return True

    def reject(self):
        return True


class BulletEmitterViewProvider:
    def __init__(self, vobj):
        vobj.Proxy = self

    def attach(self, vobj):
        self.Object = vobj.Object
        from pivy import coin
        vobj.addDisplayMode(coin.SoGroup(), "Default")

    def getDisplayModes(self, vobj):
        return ["Default"]

    def getDefaultDisplayMode(self):
        return "Default"

    def getIcon(self):
        import os
        from .. import BulletUtils
        return os.path.join(BulletUtils.ICONS_PATH, "AddEmitter.svg")

    def claimChildren(self):
        return [link for link in getattr(self.Object, "GeneratedLinks", [])
                if link is not None]

    def setEdit(self, vobj, mode):
        import FreeCADGui
        FreeCADGui.Control.showDialog(EmitterPanel(vobj.Object))
        return True

    def unsetEdit(self, vobj, mode):
        import FreeCADGui
        FreeCADGui.Control.closeDialog()
        return True

    def doubleClicked(self, vobj):
        self.setEdit(vobj, 0)
        return True

    def __getstate__(self):
        return None

    def __setstate__(self, state):
        return None


def make_emitter(source_obj, template_obj=None, container=None):
    doc = FreeCAD.ActiveDocument
    emitter = doc.addObject("App::FeaturePython", f"Emitter_{source_obj.Name}")
    BulletEmitterFeature(emitter)
    emitter.EmissionSource = source_obj
    emitter.TemplateObject = template_obj
    emitter.TemplateObjects = [template_obj] if template_obj is not None else []
    emitter.TemplateRatios = [100.0] if template_obj is not None else []
    emitter.Label = f"Emitter_{source_obj.Label}"

    if FreeCAD.GuiUp:
        BulletEmitterViewProvider(emitter.ViewObject)

    if container is not None:
        if not hasattr(container, "Emitters"):
            container.addProperty("App::PropertyLinkList", "Emitters", "Container",
                                  "Rigid body emitter objects managed by this simulation")
        current = list(getattr(container, "Emitters", []))
        current.append(emitter)
        container.Emitters = current

    doc.recompute()
    return emitter
