import FreeCAD


def _shape_objects(doc):
    return [obj for obj in doc.Objects
            if hasattr(obj, "Shape") and obj.Shape is not None]


def _parse_vector(text, fallback):
    try:
        values = [float(value.strip()) for value in text.split(",")]
        if len(values) == 3:
            return FreeCAD.Vector(*values)
    except (TypeError, ValueError):
        pass
    return fallback


class BulletEmitterFeature:
    """Non-physical configuration for spawning bodies from a source shape."""

    def __init__(self, obj):
        obj.addProperty("App::PropertyLink", "EmissionSource", "Emitter",
                        "Volume or surface used to choose emission positions")
        obj.addProperty("App::PropertyLink", "TemplateObject", "Emitter",
                        "Object copied for each emitted body")
        obj.addProperty("App::PropertyLinkList", "GeneratedLinks", "Emitter",
                        "Simulation links generated by this emitter")
        obj.addProperty("App::PropertyBool", "Enabled", "Emitter",
                        "Include this emitter in Bullet Physics simulations")
        obj.Enabled = True
        obj.addProperty("App::PropertyEnumeration", "BodyType", "Emission",
                        "Type assigned to each emitted body; the emitter is non-physical")
        obj.BodyType = ["Active", "Passive"]
        obj.addProperty("App::PropertyInteger", "Count", "Emission",
                        "Total number of bodies to emit")
        obj.Count = 1
        obj.addProperty("App::PropertyFloat", "StartTime", "Emission",
                        "Simulation time in seconds for the first emission")
        obj.StartTime = 0.0
        obj.addProperty("App::PropertyFloat", "EndTime", "Emission",
                        "Simulation time in seconds for the final emission")
        obj.EndTime = 1.0
        obj.addProperty("App::PropertyVector", "Orientation", "Emission",
                        "Base emitted orientation in degrees (X, Y, Z)")
        obj.Orientation = FreeCAD.Vector(0, 0, 0)
        obj.addProperty("App::PropertyVector", "OrientationRandomness", "Emission",
                        "Per-axis orientation randomness: 0 = none, 1 = maximum")
        obj.OrientationRandomness = FreeCAD.Vector(0, 0, 0)
        obj.addProperty("App::PropertyFloat", "Velocity", "Active Body",
                        "Initial launch speed in m/s. Ignored for Passive bodies")
        obj.Velocity = 0.0
        obj.addProperty("App::PropertyVector", "Direction", "Active Body",
                        "Initial launch direction. Ignored for Passive bodies")
        obj.Direction = FreeCAD.Vector(0, 0, 1)
        obj.addProperty("App::PropertyFloat", "Density", "Active Body",
                        "Material density in kg/m³ for active emitted bodies")
        obj.Density = 1000.0
        obj.addProperty("App::PropertyFloat", "Restitution", "Material",
                        "Bounciness from 0 to 1")
        obj.Restitution = 0.3
        obj.addProperty("App::PropertyFloat", "Friction", "Material",
                        "Friction coefficient")
        obj.Friction = 0.5
        obj.Proxy = self

    def execute(self, obj):
        pass

    def onDocumentRestored(self, obj):
        if not hasattr(obj, "GeneratedLinks"):
            obj.addProperty("App::PropertyLinkList", "GeneratedLinks", "Emitter",
                            "Simulation links generated by this emitter")
        if not hasattr(obj, "Enabled"):
            obj.addProperty("App::PropertyBool", "Enabled", "Emitter",
                            "Include this emitter in Bullet Physics simulations")
            obj.Enabled = True

    def __getstate__(self):
        return None

    def __setstate__(self, state):
        return None


class EmitterPanel:
    """Task panel for selecting an emission source and emitted object."""

    def __init__(self, emitter):
        from PySide import QtWidgets

        self._emitter = emitter
        self.form = QtWidgets.QWidget()
        self.form.setWindowTitle("Emitter")
        layout = QtWidgets.QVBoxLayout(self.form)

        source_group = QtWidgets.QGroupBox("Objects")
        source_form = QtWidgets.QFormLayout(source_group)
        self.source_combo = QtWidgets.QComboBox()
        self.template_combo = QtWidgets.QComboBox()
        self._populate_object_combos()
        source_form.addRow("Emission source:", self.source_combo)
        source_form.addRow("Object to emit:", self.template_combo)
        layout.addWidget(source_group)

        emission_group = QtWidgets.QGroupBox("Emission")
        emission_form = QtWidgets.QFormLayout(emission_group)
        self.enabled_check = QtWidgets.QCheckBox("Enabled")
        self.enabled_check.setChecked(getattr(emitter, "Enabled", True))
        self.type_combo = QtWidgets.QComboBox()
        self.type_combo.addItems(["Active", "Passive"])
        self.type_combo.setCurrentText(getattr(emitter, "BodyType", "Active"))
        self.count_spin = QtWidgets.QSpinBox()
        self.count_spin.setRange(1, 10000)
        self.count_spin.setValue(max(1, getattr(emitter, "Count", 1)))
        self.start_spin = self._time_spin(getattr(emitter, "StartTime", 0.0))
        self.end_spin = self._time_spin(getattr(emitter, "EndTime", 1.0))
        self.orientation_edit = QtWidgets.QLineEdit(self._vector_text(emitter.Orientation))
        self.randomness_edit = QtWidgets.QLineEdit(
            self._vector_text(emitter.OrientationRandomness))
        self.orientation_edit.setToolTip("Euler angles in degrees: X, Y, Z")
        self.randomness_edit.setToolTip("Per-axis values from 0 (none) to 1 (maximum)")
        emission_form.addRow(self.enabled_check)
        emission_form.addRow("Emitted body type:", self.type_combo)
        emission_form.addRow("Count:", self.count_spin)
        emission_form.addRow("Start time (s):", self.start_spin)
        emission_form.addRow("End time (s):", self.end_spin)
        emission_form.addRow("Orientation (deg):", self.orientation_edit)
        emission_form.addRow("Orientation randomness:", self.randomness_edit)
        layout.addWidget(emission_group)

        launch_group = QtWidgets.QGroupBox("Active Body Launch")
        launch_form = QtWidgets.QFormLayout(launch_group)
        self.velocity_spin = QtWidgets.QDoubleSpinBox()
        self.velocity_spin.setRange(0.0, 100000.0)
        self.velocity_spin.setDecimals(4)
        self.velocity_spin.setSuffix(" m/s")
        self.velocity_spin.setValue(max(0.0, getattr(emitter, "Velocity", 0.0)))
        self.direction_edit = QtWidgets.QLineEdit(self._vector_text(emitter.Direction))
        self.direction_edit.setToolTip("Direction vector: X, Y, Z")
        self.passive_note = QtWidgets.QLabel("Passive object selected: velocity and direction are ignored.")
        self.passive_note.setWordWrap(True)
        launch_form.addRow("Velocity:", self.velocity_spin)
        launch_form.addRow("Direction:", self.direction_edit)
        launch_form.addRow(self.passive_note)
        layout.addWidget(launch_group)
        layout.addStretch()

        self.source_combo.currentIndexChanged.connect(self._save)
        self.template_combo.currentIndexChanged.connect(self._save)
        self.enabled_check.toggled.connect(self._save)
        self.type_combo.currentTextChanged.connect(self._on_type_changed)
        self.count_spin.valueChanged.connect(self._save)
        self.start_spin.valueChanged.connect(self._save)
        self.end_spin.valueChanged.connect(self._save)
        self.orientation_edit.editingFinished.connect(self._save)
        self.randomness_edit.editingFinished.connect(self._save)
        self.velocity_spin.valueChanged.connect(self._save)
        self.direction_edit.editingFinished.connect(self._save)
        self._update_body_type()

    @staticmethod
    def _vector_text(vector):
        return f"{vector.x:.4f}, {vector.y:.4f}, {vector.z:.4f}"

    @staticmethod
    def _time_spin(value):
        from PySide import QtWidgets
        spin = QtWidgets.QDoubleSpinBox()
        spin.setRange(0.0, 100000.0)
        spin.setDecimals(4)
        spin.setValue(max(0.0, value))
        return spin

    def _populate_object_combos(self):
        for combo, current in ((self.source_combo, self._emitter.EmissionSource),
                               (self.template_combo, self._emitter.TemplateObject)):
            combo.blockSignals(True)
            combo.clear()
            combo.addItem("(none)", None)
            selected = 0
            for obj in _shape_objects(self._emitter.Document):
                combo.addItem(obj.Label, obj)
                if obj == current:
                    selected = combo.count() - 1
            combo.setCurrentIndex(selected)
            combo.blockSignals(False)

    def _save(self, *_args):
        emitter = self._emitter
        emitter.EmissionSource = self.source_combo.currentData()
        emitter.TemplateObject = self.template_combo.currentData()
        emitter.Enabled = self.enabled_check.isChecked()
        emitter.BodyType = self.type_combo.currentText()
        emitter.Count = self.count_spin.value()
        emitter.StartTime = self.start_spin.value()
        emitter.EndTime = self.end_spin.value()
        emitter.Orientation = _parse_vector(self.orientation_edit.text(), emitter.Orientation)
        emitter.OrientationRandomness = _parse_vector(
            self.randomness_edit.text(), emitter.OrientationRandomness)
        emitter.Velocity = self.velocity_spin.value()
        emitter.Direction = _parse_vector(self.direction_edit.text(), emitter.Direction)
        emitter.Document.recompute()

    def _on_type_changed(self, *_args):
        self._update_body_type()
        self._save()

    def _update_body_type(self):
        passive = self.type_combo.currentText() == "Passive"
        self.velocity_spin.setEnabled(not passive)
        self.direction_edit.setEnabled(not passive)
        self.passive_note.setVisible(passive)

    def accept(self):
        self._save()
        return True

    def reject(self):
        return True


class BulletEmitterViewProvider:
    def __init__(self, vobj):
        vobj.Proxy = self

    def attach(self, vobj):
        self.Object = vobj.Object
        from pivy import coin
        vobj.addDisplayMode(coin.SoGroup(), "Default")

    def getDisplayModes(self, vobj):
        return ["Default"]

    def getDefaultDisplayMode(self):
        return "Default"

    def getIcon(self):
        import os
        from .. import BulletUtils
        return os.path.join(BulletUtils.ICONS_PATH, "AddEmitter.svg")

    def claimChildren(self):
        return [link for link in getattr(self.Object, "GeneratedLinks", [])
                if link is not None]

    def setEdit(self, vobj, mode):
        import FreeCADGui
        FreeCADGui.Control.showDialog(EmitterPanel(vobj.Object))
        return True

    def unsetEdit(self, vobj, mode):
        import FreeCADGui
        FreeCADGui.Control.closeDialog()
        return True

    def doubleClicked(self, vobj):
        self.setEdit(vobj, 0)
        return True

    def __getstate__(self):
        return None

    def __setstate__(self, state):
        return None


def make_emitter(source_obj, template_obj=None, container=None):
    doc = FreeCAD.ActiveDocument
    emitter = doc.addObject("App::FeaturePython", f"Emitter_{source_obj.Name}")
    BulletEmitterFeature(emitter)
    emitter.EmissionSource = source_obj
    emitter.TemplateObject = template_obj
    emitter.Label = f"Emitter_{source_obj.Label}"

    if FreeCAD.GuiUp:
        BulletEmitterViewProvider(emitter.ViewObject)

    if container is not None:
        if not hasattr(container, "Emitters"):
            container.addProperty("App::PropertyLinkList", "Emitters", "Container",
                                  "Rigid body emitter objects managed by this simulation")
        current = list(getattr(container, "Emitters", []))
        current.append(emitter)
        container.Emitters = current

    doc.recompute()
    return emitter
